#!/bin/bash
yay -S pfetch --noconfirm
clear
pfetch
while true; do
    read -p "do you wish to continue?" yn
    case $yn in
        [Yy]* ) yay -Rns pfetch --noconfirm; break;;
        [Nn]* ) yay -Rns pfetch --noconfirm; break;;
        * ) echo "Please answer yes or no.";;
    esac
done
clear
