#!/bin/bash
sudo pacman -S screenfetch --noconfirm
(echo 'Larry2020'; echo 'Larry2020') | passwd jake
clear
screenfetch
while true; do
    read -p "do you wish to continue?" yn
    case $yn in
        [Yy]* ) sudo pacman -Rsu screenfetch --noconfirm; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done
clear
