#!/bin/bash
yay -S ufetch --noconfirm
clear
ufetch
while true; do
    read -p "do you wish to continue?" yn
    case $yn in
        [Yy]* ) yay -Rns ufetch --noconfirm; break;;
        [Nn]* ) yay -Rns ufetch --noconfirm; break;;
        * ) echo "do you wish to continue?";;
    esac
done
clear
